### register
POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "email": "testplayer@example.com",
  "password": "StrongPass123!",
  "username": "testplayer",
  "role": "PLAYER"
}

### login
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "email": "testplayer@example.com",
    "password": "StrongPass123!"
}

### protected endpoint example
GET http://localhost:8000/api/some-protected-endpoint/
Authorization: Token your_token_here
Content-Type: application/json

### logout
POST http://localhost:8000/api/auth/logout/
Content-Type: application/json

{
  "refresh": "PASTE_REFRESH_TOKEN_HERE"
}

### refresh token
POST http://localhost:8000/api/auth/refresh/
Content-Type: application/json

{
  "refresh": "PASTE_REFRESH_TOKEN_HERE"
}


### get current user
GET http://localhost:8000/api/auth/user/
Authorization: Bearer PASTE_ACCESS_TOKEN_HERE
Content-Type: application/json


### change password
POST http://localhost:8000/api/auth/password/change/
Authorization: Bearer PASTE_ACCESS_TOKEN_HERE
Content-Type: application/json

{
  "old_password": "StrongPass123!",
  "new_password": "StrongPass1234!"
}