# Generated by Django 5.2.7 on 2025-11-14 18:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('account_type', models.CharField(choices=[('PLAYER', 'Player'), ('CLUB', 'Club'), ('ADMIN', 'Admin')], default='PLAYER', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userid', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, db_column='firstName', max_length=40)),
                ('last_name', models.CharField(blank=True, db_column='lastName', max_length=40)),
                ('can_manage_users', models.BooleanField(db_column='canManageUsers', default=True)),
                ('can_manage_bookings', models.BooleanField(db_column='canManageBookings', default=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('userid', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='club', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('address', models.CharField(blank=True, db_column='address', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description')),
                ('working_hours', models.CharField(blank=True, db_column='workingHours', max_length=100)),
                ('contact_number', models.CharField(blank=True, db_column='contactNumber', max_length=20)),
                ('rating_avg', models.DecimalField(db_column='ratingAvg', decimal_places=2, default=0.0, max_digits=3)),
            ],
            options={
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('userid', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, db_column='firstName', max_length=40)),
                ('last_name', models.CharField(blank=True, db_column='lastName', max_length=40)),
                ('phone_number', models.CharField(blank=True, db_column='phoneNumber', max_length=20)),
                ('skill_level', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCED', 'ADVANCED'), ('PROFESSIONAL', 'PROFESSIONAL')], db_column='skillLevel', default='BEGINNER', max_length=20)),
                ('preferred_dow', models.IntegerField(db_column='preferredDow', default=0, null=True)),
                ('preferred_time', models.TimeField(db_column='preferredTime', default=datetime.time(9, 30), null=True)),
            ],
            options={
                'db_table': 'player',
            },
        ),
    ]
