# Generated by Django 5.2.7 on 2026-01-23 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description')),
                ('monthly_price', models.DecimalField(db_column='monthlyPrice', decimal_places=2, max_digits=12)),
                ('offer_type', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('TUTORING', 'Tutoring')], db_column='offerType', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='startedAt')),
                ('clubid', models.ForeignKey(db_column='clubId', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.club')),
            ],
            options={
                'db_table': 'offer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='subscription_only',
            field=models.BooleanField(db_column='subscriptionOnly', default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='reservation_fee',
            field=models.DecimalField(db_column='reservationFee', decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='notification',
            name='reservation',
            field=models.ForeignKey(blank=True, db_column='reservationId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_column='approvalStatus', default='APPROVED', max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('offer', models.OneToOneField(db_column='offerId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscription', serialize=False, to='api.offer')),
                ('discount_percentage', models.IntegerField(db_column='discountPercentage')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='Tutoring',
            fields=[
                ('offer', models.OneToOneField(db_column='offerId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tutoring', serialize=False, to='api.offer')),
                ('tutor_name', models.CharField(db_column='tutorName', max_length=100)),
            ],
            options={
                'db_table': 'tutoring',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, db_table='booking_subscription', related_name='bookings', to='api.subscription'),
        ),
        migrations.CreateModel(
            name='PlayerOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paypal_order_id', models.CharField(blank=True, db_column='paypalOrderId', max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_column='paymentStatus', default='PENDING', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True, db_column='purchasedAt')),
                ('expires_at', models.DateTimeField(db_column='expiresAt')),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_offers', to='api.offer')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_offers', to='api.player')),
            ],
            options={
                'db_table': 'player_offer',
                'ordering': ['-purchased_at'],
                'unique_together': {('player', 'offer')},
            },
        ),
    ]
