# Generated by Django 5.2.7 on 2026-01-20 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='comment', max_length=300)),
                ('rating', models.DecimalField(db_column='rating', decimal_places=2, max_digits=3)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='uploadedAt')),
                ('clubid', models.ForeignKey(db_column='clubId', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
