# Generated by Django 5.2.7 on 2025-11-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_type',
            new_name='role',
        ),
    ]
