# Generated by Django 5.2.7 on 2026-01-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='repeating',
            field=models.BooleanField(db_column='repeating', default=False),
        ),
    ]
