# Generated by Django 5.2.7 on 2025-11-11 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='userid',
            field=models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='userid',
            field=models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='club', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='userid',
            field=models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
