# Generated by Django 5.2.7 on 2025-11-14 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_role_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='preferred_dow',
            field=models.IntegerField(db_column='preferredDow', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_time',
            field=models.TimeField(db_column='preferredTime', default=datetime.time(9, 30), null=True),
        ),
    ]
