# Generated by Django 5.2.7 on 2026-01-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_offer_tutoring_subscription_playeroffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='eligible_bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, db_table='booking_subscription', related_name='bookings', to='api.subscription'),
        ),
    ]
