# Generated by Django 5.2.7 on 2026-01-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_subscription_eligible_bookings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_column='approvalStatus', default='APPROVED', max_length=20),
        ),
    ]
