# Generated by Django 5.2.7 on 2026-01-23 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_price_reservation_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reservation',
            field=models.ForeignKey(blank=True, db_column='reservationId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.reservation'),
        ),
    ]
