# Generated by Django 5.2.7 on 2026-01-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='reservation_fee',
            field=models.DecimalField(db_column='reservationFee', decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
