# Generated by Django 5.2.7 on 2026-01-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_field_reservation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='subscription_only',
            field=models.BooleanField(db_column='subscriptionOnly', default=False),
        ),
    ]
