# Generated by Django 5.2.7 on 2026-01-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_offer_booking_price_booking_subscription_only_and_more'),
        ('api', '0008_booking_subscription_only'),
    ]

    operations = [
    ]
