from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('auth/login/', views.login, name="login"),
    path('auth/register/', views.register, name="register"),
    path('auth/google/check/', views.google_check, name="google_check"),
    path('auth/google/register/', views.google_register, name="google_register"),
    path('auth/google/login/', views.google_login, name="google_login"),
    path('auth/logout/', views.logout, name='logout'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('auth/user/', views.current_user, name='current_user'),
    path('auth/user/update/', views.update_user, name='update_user'),
    path('auth/user/delete/', views.delete_account, name='delete_account'),
    path('auth/password/change/', views.change_password, name='change_password'),
    path('search/', views.search, name="search"),
    path('fields/', views.list_fields, name='list_fields'),
    path('fields/create/', views.create_field, name='create_field'),
    path('fields/<int:field_id>/', views.get_field, name='get_field'),
    path('fields/<int:field_id>/update/', views.update_field, name='update_field'),
    path('fields/<int:field_id>/delete/', views.delete_field, name='delete_field'),
    path('fields/<int:field_id>/bookings/', views.get_field_bookings, name='get_field_bookings'),
    path('fields/<int:field_id>/bookings/create/', views.create_booking, name='create_booking'),
    path('fields/<int:field_id>/bookings/<int:booking_id>/', views.update_booking, name='update_booking'),
    path('fields/<int:field_id>/bookings/<int:booking_id>/delete/', views.delete_booking, name='delete_booking'),
    path('fields/<int:field_id>/public/', views.get_public_field, name='get_public_field'),
    path('fields/<int:field_id>/bookings/public/', views.get_public_field_bookings, name='get_public_field_bookings'),
    path('fields/<int:field_id>/reserve/', views.reserve_booking, name='reserve_booking'),
    path('fields/<int:field_id>/reservations/', views.get_field_reservations, name='get_field_reservations'),
    path('clubs/<int:club_id>/', views.get_club, name='get_club'),
    path('reservations/', views.get_all_player_reservations, name='get_all_player_reservations'),
    path('reservations/<int:reservation_id>/', views.delete_reservation, name='delete_reservation'),
    path('reviews/', views.create_review, name='create_review'),
    path('reviews/user/<int:user_id>/', views.get_reviews_by_user, name='get_reviews_by_user'),
    path('reviews/club/<int:club_id>/', views.get_reviews_by_club, name='get_reviews_by_club'),
    path('reviews/<int:review_id>/', views.delete_review, name='delete_review'),
]